<?xml version="1.0"?>
<robot>
  <!--macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
      iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
      izz="${m*r*r/2}"
    />
  </macro>

  <macro name="box_inertia" params="m x y z">
    <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
      iyy="${m*(x*x+z*z)/12}" iyz = "0"
      izz="${m*(x*x+z*z)/12}"
    />
  </macro>

  <macro name="sphere_inertia" params="m r">
    <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
      iyy="${2*m*r*r/5}" iyz = "0"
      izz="${2*m*r*r/5}"
    />
  </macro>







  <macro name="wheel" params="lr tY">

    <link name="${lr}_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
        <geometry>
          <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
        <geometry>
          <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
        </geometry>
        <material name="black"/>process[master]: started with pid [10992]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 34f3e4e8-c3b0-11e9-a531-7c7635c43f51
process[rosout-1]: started with pid [11006]
started core service [/rosout]
process[gazebo-2]: started with pid [11013]
process[gazebo_gui-3]: started with pid [11030]
[ INFO] [1566349719.491559868]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.492532948]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349719.534836109]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.536242329]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349721.085791874, 0.022process[master]: started with pid [10992]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 34f3e4e8-c3b0-11e9-a531-7c7635c43f51
process[rosout-1]: started with pid [11006]
started core service [/rosout]
process[gazebo-2]: started with pid [11013]
process[gazebo_gui-3]: started with pid [11030]
[ INFO] [1566349719.491559868]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.492532948]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349719.534836109]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.536242329]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349721.085791874, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.115938409, 0.051000000]: Physics dynamic reconfigure ready.
[ INFO] [1566349721.342863690, 0.273000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.370021930, 0.300000000]: Physics dynamic reconfigure ready.
000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.115938409, 0.051process[master]: started with pid [10992]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 34f3e4e8-c3b0-11e9-a531-7c7635c43f51
process[rosout-1]: started with pid [11006]
started core service [/rosout]
process[gazebo-2]: started with pid [11013]
process[gazebo_gui-3]: started with pid [11030]
[ INFO] [1566349719.491559868]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.492532948]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349719.534836109]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.536242329]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349721.085791874, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.115938409, 0.051000000]: Physics dynamic reconfigure ready.
[ INFO] [1566349721.342863690, 0.273000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.370021930, 0.300000000]: Physics dynamic reconfigure ready.
000000]: Physics dynamic reconfigure ready.
[ INFO] [1566349721.342863690, 0.273process[master]: started with pid [10992]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 34f3e4e8-c3b0-11e9-a531-7c7635c43f51
process[rosout-1]: started with pid [11006]
started core service [/rosout]
process[gazebo-2]: started with pid [11013]
process[gazebo_gui-3]: started with pid [11030]
[ INFO] [1566349719.491559868]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.492532948]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349719.534836109]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.536242329]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349721.085791874, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.115938409, 0.051000000]: Physics dynamic reconfigure ready.
[ INFO] [1566349721.342863690, 0.273000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.370021930, 0.300000000]: Physics dynamic reconfigure ready.
000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.370021930, 0.300process[master]: started with pid [10992]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 34f3e4e8-c3b0-11e9-a531-7c7635c43f51
process[rosout-1]: started with pid [11006]
started core service [/rosout]
process[gazebo-2]: started with pid [11013]
process[gazebo_gui-3]: started with pid [11030]
[ INFO] [1566349719.491559868]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.492532948]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349719.534836109]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.536242329]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349721.085791874, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.115938409, 0.051000000]: Physics dynamic reconfigure ready.
[ INFO] [1566349721.342863690, 0.273000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.370021930, 0.300000000]: Physics dynamic reconfigure ready.
000000]: Physics dynamic reconfigure ready.
process[master]: started with pid [10992]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 34f3e4e8-c3b0-11e9-a531-7c7635c43f51
process[rosout-1]: started with pid [11006]
started core service [/rosout]
process[gazebo-2]: started with pid [11013]
process[gazebo_gui-3]: started with pid [11030]
[ INFO] [1566349719.491559868]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.492532948]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349719.534836109]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.536242329]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349721.085791874, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.115938409, 0.051000000]: Physics dynamic reconfigure ready.
[ INFO] [1566349721.342863690, 0.273000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.370021930, 0.300000000]: Physics dynamic reconfigure ready.

      </visual>process[master]: started with pid [10992]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 34f3e4e8-c3b0-11e9-a531-7c7635c43f51
process[rosout-1]: started with pid [11006]
started core service [/rosout]
process[gazebo-2]: started with pid [11013]
process[gazebo_gui-3]: started with pid [11030]
[ INFO] [1566349719.491559868]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.492532948]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349719.534836109]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.536242329]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349721.085791874, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.115938409, 0.051000000]: Physics dynamic reconfigure ready.
[ INFO] [1566349721.342863690, 0.273000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.370021930, 0.300000000]: Physics dynamic reconfigure ready.

process[master]: started with pid [10992]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 34f3e4e8-c3b0-11e9-a531-7c7635c43f51
process[rosout-1]: started with pid [11006]
started core service [/rosout]
process[gazebo-2]: started with pid [11013]
process[gazebo_gui-3]: started with pid [11030]
[ INFO] [1566349719.491559868]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.492532948]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349719.534836109]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.536242329]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349721.085791874, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.115938409, 0.051000000]: Physics dynamic reconfigure ready.
[ INFO] [1566349721.342863690, 0.273000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.370021930, 0.300000000]: Physics dynamic reconfigure ready.

      <inertial>process[master]: started with pid [10992]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 34f3e4e8-c3b0-11e9-a531-7c7635c43f51
process[rosout-1]: started with pid [11006]
started core service [/rosout]
process[gazebo-2]: started with pid [11013]
process[gazebo_gui-3]: started with pid [11030]
[ INFO] [1566349719.491559868]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.492532948]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349719.534836109]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.536242329]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349721.085791874, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.115938409, 0.051000000]: Physics dynamic reconfigure ready.
[ INFO] [1566349721.342863690, 0.273000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.370021930, 0.300000000]: Physics dynamic reconfigure ready.

        <origin xyz="0 0 0" rpy="0 $process[master]: started with pid [10992]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 34f3e4e8-c3b0-11e9-a531-7c7635c43f51
process[rosout-1]: started with pid [11006]
started core service [/rosout]
process[gazebo-2]: started with pid [11013]
process[gazebo_gui-3]: started with pid [11030]
[ INFO] [1566349719.491559868]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.492532948]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349719.534836109]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.536242329]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349721.085791874, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.115938409, 0.051000000]: Physics dynamic reconfigure ready.
[ INFO] [1566349721.342863690, 0.273000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.370021930, 0.300000000]: Physics dynamic reconfigure ready.
{PI/2} ${PI/2}" />
        <mass value="${wheelMass}"/>process[master]: started with pid [10992]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 34f3e4e8-c3b0-11e9-a531-7c7635c43f51
process[rosout-1]: started with pid [11006]
started core service [/rosout]
process[gazebo-2]: started with pid [11013]
process[gazebo_gui-3]: started with pid [11030]
[ INFO] [1566349719.491559868]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.492532948]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349719.534836109]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.536242329]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349721.085791874, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.115938409, 0.051000000]: Physics dynamic reconfigure ready.
[ INFO] [1566349721.342863690, 0.273000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.370021930, 0.300000000]: Physics dynamic reconfigure ready.

        <cylinder_inertia m="${wheelprocess[master]: started with pid [10992]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 34f3e4e8-c3b0-11e9-a531-7c7635c43f51
process[rosout-1]: started with pid [11006]
started core service [/rosout]
process[gazebo-2]: started with pid [11013]
process[gazebo_gui-3]: started with pid [11030]
[ INFO] [1566349719.491559868]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.492532948]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349719.534836109]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.536242329]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349721.085791874, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.115938409, 0.051000000]: Physics dynamic reconfigure ready.
[ INFO] [1566349721.342863690, 0.273000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.370021930, 0.300000000]: Physics dynamic reconfigure ready.
Mass}" r="${wheelRadius}" h="${wheelWidth}"/>
      </inertial>process[master]: started with pid [10992]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 34f3e4e8-c3b0-11e9-a531-7c7635c43f51
process[rosout-1]: started with pid [11006]
started core service [/rosout]
process[gazebo-2]: started with pid [11013]
process[gazebo_gui-3]: started with pid [11030]
[ INFO] [1566349719.491559868]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.492532948]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349719.534836109]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.536242329]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349721.085791874, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.115938409, 0.051000000]: Physics dynamic reconfigure ready.
[ INFO] [1566349721.342863690, 0.273000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.370021930, 0.300000000]: Physics dynamic reconfigure ready.

    </link>process[master]: started with pid [10992]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 34f3e4e8-c3b0-11e9-a531-7c7635c43f51
process[rosout-1]: started with pid [11006]
started core service [/rosout]
process[gazebo-2]: started with pid [11013]
process[gazebo_gui-3]: started with pid [11030]
[ INFO] [1566349719.491559868]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.492532948]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349719.534836109]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.536242329]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349721.085791874, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.115938409, 0.051000000]: Physics dynamic reconfigure ready.
[ INFO] [1566349721.342863690, 0.273000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.370021930, 0.300000000]: Physics dynamic reconfigure ready.

process[master]: started with pid [10992]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 34f3e4e8-c3b0-11e9-a531-7c7635c43f51
process[rosout-1]: started with pid [11006]
started core service [/rosout]
process[gazebo-2]: started with pid [11013]
process[gazebo_gui-3]: started with pid [11030]
[ INFO] [1566349719.491559868]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.492532948]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349719.534836109]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566349719.536242329]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1566349721.085791874, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.115938409, 0.051000000]: Physics dynamic reconfigure ready.
[ INFO] [1566349721.342863690, 0.273000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566349721.370021930, 0.300000000]: Physics dynamic reconfigure ready.

    <gazebo reference="${lr}_wheel">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
      <kp  value="10000000.0" />
      <kd  value="1.0" />
      <fdir1 value="1 0 0"/>
      <material>Gazebo/Black</material>
    </gazebo>


    <joint name="${lr}_wheel_hinge" type="continuous">
      <parent link="chassis"/>
      <child link="${lr}_wheel"/>
    <origin xyz="${-wheelPos+chassisLength/2} ${tY*wheelWidth/2+tY*chassisWidth/2} ${wheelRadius}" rpy="0 0 0" />
      <axis xyz="0 1 0" rpy="0 0 0" />
      <limit effort="10000" velocity="10000"/>
      <joint_properties damping="0.0" friction="0.0"/>
    </joint>


    <transmission name="${lr}_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${lr}_wheel_hinge">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${lr}Motor">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>10</mechanicalReduction>
      </actuator>
    </transmission>

  </macro-->





</robot>
